default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: '1625'

development:
  <<: *default
  database: appuu_dev

test: &test
  <<: *default
  database: appuu_test

production:
  <<: *default
  database: appuu

cucumber:
  <<: *test